# Generated by Django 3.2.14 on 2022-07-12 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cifrado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=500)),
                ('key', models.CharField(max_length=200)),
            ],
        ),
    ]
